#!/usr/bin/env python3

from ipaddress import IPv6Address
from sys import argv, exit

if __name__ == "__main__":
    if len(argv) > 1:
        try:
            ipv6, mask = argv[1].split('/')
            _ = IPv6Address(ipv6)
            _ = IPv6Address(mask)
        except Exception as err:
            print(f'Error: {argv[1]} is not a valid masked IPv6 address: {err}')
            exit(1)
    else:
        print('Error: a masked IPv6 argument must be provided')
        exit(1)
